version: '3'
services:
    socket:
        build:
            context: .
        ports:
            - 9011:9011
            - 8000:8000
        volumes:
            - $PWD:/usr/src/myapp:rw
        restart: always
        command: ["bash","/usr/src/myapp/start.sh"]
        container_name: python_socket

networks:
    default:
        external:
            name:  sz_web_net