# Generated by Django 2.2 on 2019-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string1', models.TextField(max_length=2048)),
                ('string2', models.TextField(max_length=2048)),
                ('flag1', models.CharField(max_length=200)),
                ('flag2', models.CharField(max_length=200)),
            ],
        ),
    ]
